# Generated by Django 4.1.5 on 2023-08-01 05:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Client_side', '0005_alter_professional_fee_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfessionalAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('is_available', models.BooleanField(default=True)),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Client_side.professional')),
            ],
        ),
    ]
