# Generated by Django 4.2.3 on 2023-07-20 05:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Client_side', '0003_professional'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='staff_images/')),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Client_side.professional')),
            ],
        ),
        migrations.CreateModel(
            name='Description',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Client_side.professional')),
            ],
        ),
    ]
