# Generated by Django 4.1.5 on 2023-07-25 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client_side', '0004_image_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professional',
            name='fee_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
