# Generated by Django 4.1.5 on 2023-08-02 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Professional_side', '0002_alter_professionalavailability_end_time_and_more'),
        ('Client_side', '0006_bookings'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='availability',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='Professional_side.professionalavailability'),
        ),
        migrations.AddField(
            model_name='bookings',
            name='professional',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='Client_side.professional'),
        ),
    ]
